FROM rpy2/rpy2:latest

RUN pip install numpy scipy pandas scikit-learn click==6.7 umap-learn==0.3.7 plotly torch==0.4.1 torchvision fancyimpute==0.4.2 shap matplotlib

RUN mkdir /scripts/

RUN apt-get -y update

RUN apt-get remove curl && apt-get install -y curl

RUN apt-get remove libssl-dev && apt-get install -y libssl-dev

RUN apt-get install -y libgtk2.0-dev xvfb xauth xfonts-base libcairo2-dev libcurl4-openssl-dev # libxaw xlib

RUN apt-get install -y libx11-dev openssl libxt-dev #libxaw xlib

COPY basic_installer.py /scripts/

RUN python /scripts/basic_installer.py -p git2r Rcpp simpleCache BiocManager remotes knitr markdown gridExtra multcomp fastICA statmod lme4 Cairo

RUN python /scripts/basic_installer.py -b -p minfi ENmix geneplotter IlluminaHumanMethylation450kanno.ilmn12.hg19 sva S4Vectors DNAcopy gdsfmt illuminaio rtracklayer GEOquery LOLA limma missMethyl

RUN wget https://github.com/perishky/meffil/archive/master.zip && unzip master.zip && mv meffil-master meffil && R CMD INSTALL meffil

COPY cuda_install.sh .

RUN sh cuda_install.sh && echo "cuda_install complete"
